version: '3.7'

services:
  db: 
    image: mysql
    container_name: faceoff-db
    ports: 
      - 3306:3306
      - 33060:33060
    volumes:
      - /home/faceoff/db_data/:/var/lib/mysql
      - /home/faceoff/db_config/:/usr/src/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: FaceoffAIRocks
      MYSQL_DATABASE: faceoff
      MYSQL_USER: faceoff
      MYSQL_PASSWORD: FaceoffAIRocks

  backend:
    build: ./backend 
    container_name: faceoff-backend
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    ports: 
      - 8080:8080
    depends_on:
      - db
    
    