version: '3.7'

services:
  db: 
    image: mysql
    container_name: faceoff-db
    ports: 
      - 3306:3306
      - 33060:33060
    volumes:
      - /home/faceoff/db_data/:/var/lib/mysql
      - /home/faceoff/db_config/:/usr/src/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: FaceoffAIRocks
      MYSQL_DATABASE: faceoff
      MYSQL_USER: faceoff
      MYSQL_PASSWORD: FaceoffAIRocks

  backend:
    build: ./backend 
    container_name: faceoff-backend
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /home/faceoff/.security/:/usr/src/app/auth/keys/
      - /home/faceoff/https/:/usr/src/app/https/
    depends_on:
      - db
    
  nginx:
    image: nginx
    container_name: faceoff-load
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/faceoff/https/:/etc/nginx/ssl
    