version: '3.7'

services:
  db: 
    image: mysql
    container_name: faceoff-db
    ports: 
      - 3306:3306
      - 33060:33060
    volumes:
      - /home/faceoff/db_data/:/var/lib/mysql
      - /home/faceoff/db_config/:/usr/src/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: FaceoffAIRocks
      MYSQL_DATABASE: faceoff
      MYSQL_USER: faceoff
      MYSQL_PASSWORD: FaceoffAIRocks
    
  # nginx:
  #   image: nginx
  #   container_name: faceoff-load
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - /home/faceoff/https/:/etc/nginx/ssl/
  #   depends_on:
  #     - backend

  proxy:
    image: traefik:v2.3
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker
    ports:
      - 80:80
      - 443:443
      - 8081:8080 #Use 8081 to configure traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.http.routers.dash.rule: Host(`dash.localhost`)
      traefik.http.routers.dash.service: api@internal
      traefik.http.routers.dash.tls: false

  backend:
    build: ./backend 
    container_name: faceoff-backend
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    environment:
      PORT: 8080
    ports: 
      - 8080:8080
    volumes:
      - /home/faceoff/.security/:/usr/src/app/auth/keys/
      # - /home/faceoff/https/:/usr/src/app/https/
    depends_on:
      - db
    