global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

http:
  routers:
    backend:
      rule: "Host(`ai.faceoff.cf`)"
      service: "backend-face-off-ai@docker"
      tls: {}
      entryPoints:
        - websecure

tls:
  certificates:
    - certFile: /usr/cert/cert.pem
      keyFile: /usr/cert/priv.pem

providers:
  docker:
    exposedByDefault: true
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true