global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

tls:
  certificates:
    - certFile: /usr/cert/cert.pem
      keyFile: /usr/cert/priv.pem


providers:
  docker:
    exposedByDefault: true